export { default as Header } from "./Header";
export { default as Hero } from "./Hero";
export { default as LogoTicker } from "./LogoTicker";
export { default as ProductShowcase } from "./ProductShowcase";
export { default as Testimonials } from "./Testimonials";
export { default as CallToAction } from "./CallToAction";
export { default as Footer } from "./Footer";
export { default as Collaboration } from "./Collaboration";
export { default as LogoText } from "./LogoText";
